# Site
title:              Yuan-Yao Lou
bio:                'Ph.D. Student / ECE / Purdue'
description:        "Ph.D. Student / ECE / Purdue"
reading_time:       false
words_per_minute:   200
logo:               'assets/img/profile-rd.png'
background:         # 'assets/img/bg.jpeg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
# url:                http://localhost:4000     # for local development
url:                https://yylou.github.io   # for deployment

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
email:              yylou@purdue.edu
github-url:         yylou
linkedin:           yylou
# instagram:          yylou
google:
  analytics:        G-TKJ4H24F0F
  # plus:           username
  # verify:
  # ad-client:
  # ad-slot:
# bing-verify:
# twitter:          username
# facebook:         username
# stackoverflow:    123456/username   from a "http://stackoverflow.com/users/123456/username" link
# xing:             username
# lastfm:           username
# tumblr:           username
# medium:           '@username'
# pinterest:        username
# foursquare:       username
# steam:             username
# dribbble:         username
# youtube:          username
# youtube-channel:  channel
# soundcloud:       username
# weibo:            username
# flickr:           username
# codepen:          username
# keybase:          username
# xmpp:             username@server.com
# hackernews:       username
# resume:           username

# Gems
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, .ruby-version]

webrick:
  headers:
    Access-Control-Allow-Origin: "*"
